# Generated by Django 3.1.12 on 2021-06-21 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 19, 32, 57, 359564, tzinfo=utc)),
        ),
    ]
