# Generated by Django 3.1.12 on 2021-06-16 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('profile', models.ImageField(default='T-Kart/images/Customer/default-image.jpg', upload_to='T-Kart/images/Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_slug', models.SlugField(default=models.CharField(max_length=300), editable=False, max_length=300, unique=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0)),
                ('discription', models.CharField(max_length=700)),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='T-Kart/images/Products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('company_name', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=100)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('pincode', models.IntegerField()),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 16, 12, 0, 43, 642663, tzinfo=utc))),
                ('status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='T_kart.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='T_kart.product')),
            ],
        ),
    ]
