# Generated by Django 3.1.12 on 2021-06-16 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('T_kart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 12, 0, 49, 876510, tzinfo=utc)),
        ),
    ]
