# Generated by Django 3.1.12 on 2021-06-16 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('T_kart', '0002_auto_20210616_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 12, 12, 32, 535321, tzinfo=utc)),
        ),
    ]
