# Generated by Django 3.1.12 on 2021-06-17 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('T_kart', '0004_auto_20210616_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 14, 34, 54, 463092, tzinfo=utc)),
        ),
    ]
