# Generated by Django 3.1.12 on 2021-06-20 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('T_kart', '0005_auto_20210617_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 20, 15, 26, 916517, tzinfo=utc)),
        ),
    ]
