# Generated by Django 3.1.12 on 2021-06-21 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('T_kart', '0006_auto_20210620_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batteries',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='camera',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='conectivity',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='graphics',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='ports',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='procesor',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='weaight',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='wireless_comunication',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 19, 32, 57, 354696, tzinfo=utc)),
        ),
    ]
